#!/usr/bin/env bash
# Refresh the list of Cloudflare edge ranges that HAProxy trusts for
# CF-Connecting-IP. Runs weekly from cloudflare-ips.timer, and once at install.
#
# The list is what makes the header safe to trust: HAProxy only rewrites the
# client address from CF-Connecting-IP when the TCP peer is in one of these
# ranges, so a direct client cannot forge it. A stale list fails closed — an
# edge that is not listed is treated like any other client — which is a
# degradation of rate limiting, never a spoofing hole.
set -euo pipefail

LIST="${CLOUDFLARE_IPS_FILE:-/etc/haproxy/cloudflare-ips.lst}"
SOURCES=(https://www.cloudflare.com/ips-v4 https://www.cloudflare.com/ips-v6)

log() { printf '[cloudflare-ips] %s\n' "$*" >&2; }
die() { printf '[cloudflare-ips] ERROR: %s\n' "$*" >&2; exit 1; }

tmp="$(mktemp "$(dirname "$LIST")/.cloudflare-ips.XXXXXX")"
trap 'rm -f "$tmp"' EXIT

{
  echo "# Cloudflare edge ranges — generated by cloudflare-ips.sh on $(date -Is); do not edit"
  for url in "${SOURCES[@]}"; do
    curl -fsS -m 20 "$url" || die "could not fetch $url"
    echo
  done
} | grep -vE '^\s*$' > "$tmp"

# Refuse to install anything that does not look like a list of CIDRs, so a
# captive portal or an outage page cannot end up as the trust list.
count="$(grep -vc '^#' "$tmp" || true)"
(( count >= 10 )) || die "only $count ranges fetched; keeping the existing list"
if grep -v '^#' "$tmp" | grep -qvE '^[0-9a-fA-F:.]+/[0-9]{1,3}$'; then
  die "fetched list contains something that is not a CIDR; keeping the existing list"
fi

# Compare ignoring the timestamp line, so an unchanged list does not reload.
if [[ -f "$LIST" ]] && cmp -s <(grep -v '^#' "$tmp") <(grep -v '^#' "$LIST"); then
  log "unchanged ($count ranges)"
  exit 0
fi

install -o root -g haproxy -m 0640 "$tmp" "$LIST"
log "updated: $count ranges"

# HAProxy reads the file at load time, so a change needs a reload.
if systemctl is-active --quiet haproxy; then
  if haproxy -c -f /etc/haproxy/haproxy.cfg -f /etc/haproxy/conf.d >/dev/null 2>&1; then
    systemctl reload haproxy
    log "haproxy reloaded"
  else
    log "haproxy config did not validate; not reloading"
  fi
fi
