#!/usr/bin/env bash
# Manage TLS passthrough domains.
#
# The routing table lives at /etc/haproxy/passthrough.conf, outside the git
# repository, because the hostnames and internal ports in it are yours. This
# script is the only thing that reads it, and it regenerates two files HAProxy
# consumes:
#
#   /etc/haproxy/sni-passthrough.map     SNI hostname -> backend name
#   /etc/haproxy/conf.d/10-passthrough.cfg   the backend definitions
#
# Both are generated; edit passthrough.conf, never them.
set -euo pipefail

TABLE="${PASSTHROUGH_TABLE:-/etc/haproxy/passthrough.conf}"
MAP="${PASSTHROUGH_MAP:-/etc/haproxy/sni-passthrough.map}"
CONF_D="${HAPROXY_CONF_D:-/etc/haproxy/conf.d}"
GENERATED="$CONF_D/10-passthrough.cfg"
MAIN_CFG="${HAPROXY_MAIN_CFG:-/etc/haproxy/haproxy.cfg}"

log()  { printf '[passthrough] %s\n' "$*" >&2; }
die()  { printf '[passthrough] ERROR: %s\n' "$*" >&2; exit 1; }

# Mutating commands need write access to the routing table and HAProxy's config
# directory. Testing for writability rather than for uid 0 keeps the script
# runnable against overridden paths, which is how it is exercised in CI.
require_writable() {
  local d
  for d in "$(dirname "$TABLE")" "$CONF_D" "$(dirname "$MAP")"; do
    [[ -d "$d" ]] || continue
    [[ -w "$d" ]] || die "cannot write to $d (try: sudo $0 $*)"
  done
}

usage() {
  cat >&2 <<EOF
usage: $0 <command> [args]

  list                       Show the configured passthrough domains
  add <domain> <host:port>   Add a domain and apply
  remove <domain>            Remove a domain and apply
  sync                       Regenerate, validate and reload after editing
                             $TABLE by hand

Adding a domain by hand is just a line in $TABLE followed by '$0 sync'.
EOF
  exit 1
}

# backend_name turns a hostname into a valid, collision-free HAProxy identifier.
backend_name() {
  printf 'be_pt_%s' "$(printf '%s' "$1" | tr '[:upper:]' '[:lower:]' | tr -c 'a-z0-9' '_')"
}

ensure_table() {
  if [[ ! -f "$TABLE" ]]; then
    install -m 0640 /dev/null "$TABLE"
    printf '# domain                     target\n' > "$TABLE"
    log "created an empty $TABLE"
  fi
}

# read_table emits "domain<TAB>target" for each active line.
read_table() {
  ensure_table
  local domain target rest
  while read -r domain target rest; do
    [[ -z "${domain:-}" || "${domain:0:1}" == "#" ]] && continue
    [[ -n "${target:-}" ]] || die "line for '$domain' in $TABLE has no target"
    [[ "$target" == *:* ]] || die "target for '$domain' must be host:port, got '$target'"
    printf '%s\t%s\n' "$domain" "$target"
  done < "$TABLE"
}

cmd_list() {
  [[ -f "$TABLE" ]] || { log "no routing table at $TABLE — nothing configured"; return 0; }
  local any=0
  printf '%-36s %s\n' "DOMAIN" "TARGET" >&2
  while IFS=$'\t' read -r domain target; do
    any=1
    # Flag a target with nothing behind it: the domain would resolve, connect,
    # and then fail in a way that looks like a proxy fault rather than a
    # missing backend service.
    local state=""
    ss -ltnH 2>/dev/null | awk '{print $4}' | grep -qE "[:.]${target##*:}\$" \
      || state="<- nothing listening"
    printf '%-36s %s %s\n' "$domain" "$target" "$state" >&2
  done < <(read_table)
  (( any )) || log "no passthrough domains configured"
}

generate() {
  install -d -m 0755 "$CONF_D"

  local tmp_map tmp_cfg count=0
  tmp_map="$(mktemp)"; tmp_cfg="$(mktemp)"

  {
    echo "# Generated by passthrough.sh from $TABLE — do not edit."
    echo "# SNI hostname -> backend name"
  } > "$tmp_map"
  {
    echo "# Generated by passthrough.sh from $TABLE — do not edit."
    echo "# TLS passthrough backends. Each keeps its own TLS termination."
    echo
  } > "$tmp_cfg"

  local domain target be
  while IFS=$'\t' read -r domain target; do
    be="$(backend_name "$domain")"
    printf '%s %s\n' "$domain" "$be" >> "$tmp_map"
    {
      printf 'backend %s\n' "$be"
      printf '    mode tcp\n'
      # These are tunnels, not requests; the default 60s would cut them.
      printf '    timeout server 1h\n'
      printf '    server target %s\n\n' "$target"
    } >> "$tmp_cfg"
    count=$((count + 1))
  done < <(read_table)

  install -m 0644 "$tmp_map" "$MAP"
  install -m 0644 "$tmp_cfg" "$GENERATED"
  rm -f "$tmp_map" "$tmp_cfg"
  log "generated $count passthrough backend(s)"
}

validate_and_reload() {
  [[ -f "$MAIN_CFG" ]] || { log "$MAIN_CFG not present yet; generated files only"; return 0; }

  # Validate exactly the way the service starts, both config sources included.
  if ! haproxy -c -f "$MAIN_CFG" -f "$CONF_D" >/dev/null; then
    die "haproxy rejected the resulting configuration; nothing was reloaded"
  fi
  log "configuration valid"

  if systemctl is-active --quiet haproxy; then
    # reload, not restart: in-flight connections, including the passthrough
    # sessions this script just changed, are handed to the new process.
    systemctl reload haproxy
    log "haproxy reloaded"
  else
    log "haproxy is not running; start it when ready"
  fi
}

cmd_sync() { generate; validate_and_reload; }

cmd_add() {
  local domain="${1:-}" target="${2:-}"
  [[ -n "$domain" && -n "$target" ]] || die "usage: $0 add <domain> <host:port>"
  [[ "$target" == *:* ]] || die "target must be host:port, e.g. 127.0.0.1:441"
  ensure_table

  if read_table | cut -f1 | grep -qxF "$domain"; then
    die "'$domain' is already in $TABLE — remove it first, or edit the file"
  fi
  printf '%-28s %s\n' "$domain" "$target" >> "$TABLE"
  log "added $domain -> $target"
  cmd_sync
}

cmd_remove() {
  local domain="${1:-}"
  [[ -n "$domain" ]] || die "usage: $0 remove <domain>"
  ensure_table
  read_table | cut -f1 | grep -qxF "$domain" || die "'$domain' is not in $TABLE"

  local tmp; tmp="$(mktemp)"
  awk -v d="$domain" '$1 != d' "$TABLE" > "$tmp"
  install -m 0640 "$tmp" "$TABLE"
  rm -f "$tmp"
  log "removed $domain"
  cmd_sync
}

case "${1:-}" in
  list)   shift; cmd_list "$@" ;;
  add)    shift; require_writable add "$@";    cmd_add "$@" ;;
  remove) shift; require_writable remove "$@"; cmd_remove "$@" ;;
  sync)   shift; require_writable sync;        cmd_sync "$@" ;;
  *) usage ;;
esac
